@startuml
title control de deudas de alumnos
|Vicedirectora|
start
:Ya pasaron dos meses
desde que comenzaron las clases;
:buscar alumnos que pagaron parcial o que no pagaron nada;

note right
Lista de alumnos que pagaron
parcial o no pagaron nada
end note

if(lista vacía?) then (sí)
	stop
else (no)
endif

|Secretario|
repeat
:Avisar a alumno que
falta pagar la cuota;
note left
Lista de alumnos que pagaron
parcial o no pagaron nada
end note
repeat while (falta otro alumno en la lista) is (sí) not (no)

|Vicedirectora|
:Ya pasaron 3 meses
desde que comenzaron las clases;
:buscar alumnos que pagaron parcial 
(solo pagaron algunas cuotas) o 
no pagaron nada;

note right
Lista de alumnos que pagaron
parcial o no pagaron nada
end note

if(lista vacía?) then (sí)
	stop
else (no)
endif

|Secretario|
repeat
:Avisar alumno que
falta pagar la cuota;
note left
Lista de alumnos que pagaron
parcial o no pagaron nada
end note
repeat while (falta otro alumno en la lista) is (sí) not (no)

stop
@enduml
